const guideNames = [
    "#LoveOutLoud - The GamePress Entries (2021)",
    "#LoveOutLoud Content Creator Compilation (2021)",
    "(old, reference HOC page)",
    "(OUTDATED) Continuum Turbulence Ranking Guide (Archive only)",
    "(OUTDATED) Continuum Turbulence Ranking on a Budget (Archive only)",
    "(OUTDATED) CT Ranking: 1.17m Run Analysis (Archive only)",
    "(OUTDATED) CT Ranking: Playpen Unit Tracker (Archive only)",
    "(OUTDATED) CT Ranking: Turn 1-3 Tips & Tricks (Archive only)",
    "(OUTDATED) CT Ranking: Turn 4-5 Tips & Tricks (Archive only)",
    "(OUTDATED) Original CT Ranking: Military Defection Guide (Archive only)",
    "[CN] Girls' Frontline 4th Anniversary Live Stream",
    "[CN] Neural Upgrade Batch 8 Announced",
    "[CN] Project Neural Cloud, Girls' Frontline 2: Exile, Reverse Collapse & Glitch Land: October 2020 Dev Livestream",
    "[CN] Winter 2020 Event Polarized Light Leaks/Datamines & Pre-Info",
    "[CN] Winter 2020 Event Teaser",
    "[Outdated] Improving GFL performance on PC: MuMu Assistant/Nebula Engine Guide",
    "[Project Neural Cloud] Closed Beta 2 + Datamines",
    "1-4E: Advanced Training IV",
    "1-4N: Petite Courier IV",
    "2.04 Client (2019)",
    "2.09 Client Update: New Features (2022)",
    "2020 Summer Rererun Far Side of the Sea Guides & Event Info",
    "2021 Halloween Butterfly in a Cocoon Guides & Event Info",
    "2021 White Day Infinity Farming Map Guide",
    "2021 White Day The Photo Studio Mystery Guides & Event Info",
    "2022 Summer 2 The Waves Wrangler Guides & Event Info",
    "2022 White Day Event: Love Bakery",
    "2023 Summer Event Lycan Sanctuary Guides & Event Info",
    "2-4E Field Samples IV",
    "2-4N: Professional Help IV",
    "2-6: Termination",
    "2B14",
    "3-3: Covert Reinforcement",
    "3-4E: Data Retrieval IV",
    "3-4N: Anonymous Rescue IV",
    "3-6: No Hunting",
    "4-4E: Reminiscing IV",
    "4-4N: One-Week Teammates",
    "4-6: Eradicate the Disturbance",
    "5-4E: Solving the Mystery IV",
    "5-6: Order to Pursue",
    "6-4E: Final Wish IV",
    "6-6: Late Farewell",
    "A Christmas Theater Carol",
    "A Quick Guide on Mobile Special Region (a.k.a Free Svarogs) Banner",
    "A Treatise on GFL Combat - Kiting Basics",
    "Adeline Black Nyto (Protocol Assimilation)",
    "Aegis (Protocol Assimilation)",
    "Agent (Protocol Assimilation)",
    "AGS-30",
    "Alchemist (Protocol Assimilation)",
    "Alina - Mosasaur Rider (Protocol Assimilation)",
    "Alina White Nyto (Protocol Assimilation)",
    "An Introduction to Vehicles (Mobile Armor)",
    "Announcement: Rossartrist Propaganda Idol Project LIVE! (April Fools 2022)",
    "April Fools - 'Fractured Connexion' Girls Frontline x Arknight Collab Should You Farm?",
    "April Fools - 'Fractured Connexion': GFL x Arknights Collboration Event",
    "AR Overviews",
    "AR/SMG2.09",
    "Architect (Protocol Assimilation)",
    "Armored (PA)",
    "ARSMG teambuilding",
    "AT4",
    "AX2018 Girls Frontline Interview Part 2",
    "AX2018 Girls Frontline Interview Part 3",
    "Base Overview",
    "Battle Pass (Frontline Protocol) and Daily/Weekly Quest System",
    "BGM-71",
    "Bingo Event & Mystery Crate Reveal (2019)",
    "Bitter Reunion Speed Run Event (2019)",
    "Brute (Protocol Assimilation)",
    "Bug Hunting Program Information",
    "Butterfly EX nav",
    "Butterfly in a Cocoon E1-1: Midnight Pursuit",
    "Butterfly in a Cocoon E1-1: Midnight Pursuit EX",
    "Butterfly in a Cocoon E1-2: No More Omens",
    "Butterfly in a Cocoon E1-2: No More Omens EX",
    "Butterfly in a Cocoon E1-3: Broken Echoes",
    "Butterfly in a Cocoon E1-3: Broken Echoes EX",
    "Butterfly in a Cocoon EX Farming",
    "Butterfly in a Cocoon Normal Farming",
    "Butterfly Normal Nav",
    "Career Quests: The Beginning of a Great Adventure",
    "Chapter 10 Night Walkthrough and Farming Guides",
    "Chapter 10: Purgatory",
    "Chapter 10-1 Clear Guide",
    "Chapter 10-1 Emergency Clear Guide",
    "Chapter 10-1N: The Battlefield without Her I",
    "Chapter 10-2 Clear Guide",
    "Chapter 10-2 Emergency Clear Guide",
    "Chapter 10-2N: The Battlefield without Her II",
    "Chapter 10-3 Clear Guide",
    "Chapter 10-3 Emergency Clear Guide",
    "Chapter 10-3N: The Battlefield without Her III",
    "Chapter 10-4 Clear Guide",
    "Chapter 10-4 Emergency Clear Guide",
    "Chapter 10-4N: The Battlefield without Her IV",
    "Chapter 10-5 Clear Guide",
    "Chapter 10-6 Clear Guide",
    "Chapter 10N Nav Menu",
    "Chapter 11 Emergency Nav",
    "Chapter 11 Normal Nav",
    "Chapter 11 S-Rank Clear Guides",
    "Chapter 11-1: Torrent Breaker",
    "Chapter 11-1E: Strange Journey",
    "Chapter 11-2: Electronic Eye",
    "Chapter 11-2E: Plan of Attack",
    "Chapter 11-3: Silent Pursuit",
    "Chapter 11-3E: Fishing in Troubled Waters",
    "Chapter 11-4: Prior to Destruction",
    "Chapter 11-4E: Great Escape",
    "Chapter 11-5: House in the Street",
    "Chapter 11-6: Underworld",
    "Chapter 12 Nav (Emergency Default)",
    "Chapter 12 Nav (Normal Default",
    "Chapter 12 S-Rank Clear Guides",
    "Chapter 12-1: Rein Buckle",
    "Chapter 12-1E: Morning Conference I",
    "Chapter 12-1E: Morning Conference I(old)",
    "Chapter 12-2: Chasing Phantoms",
    "Chapter 12-2E: Morning Conference II",
    "Chapter 12-3: The Philosophy of Killing",
    "Chapter 12-3E: Morning Conference III",
    "Chapter 12-4: Smoke Signal",
    "Chapter 12-4E: Morning Conference IV",
    "Chapter 12-5: Ephemeral Memories",
    "Chapter 12-6: Goodbye, Daybreak",
    "Chapter 13 Emergency Nav",
    "Chapter 13 Normal Nav",
    "Chapter 13 S-Rank Clear Guides",
    "Chapter 13-1: Stay in Position",
    "Chapter 13-1E: Immemorial I",
    "Chapter 13-2: Confidential Document",
    "Chapter 13-2: Confidential Document old in case needed",
    "Chapter 13-2E: Immemorial II",
    "Chapter 13-3: Familiar Figure",
    "Chapter 13-3E: Immemorial III",
    "Chapter 13-4: Old Friend",
    "Chapter 13-4E: Immemorial IV",
    "Chapter 13-5: Closing In",
    "Chapter 13-6: Coda",
    "Chapter 8 Night Walkthrough and Farming Guides",
    "Chapter 9 Night Walkthrough and Farming Guides",
    "Chapter 9-1N: The Way Back is Paved with Light I",
    "Chapter 9-2N: The Way Back is Paved with Light II",
    "Chapter 9-3N: The Way Back is Paved with Light III",
    "Chapter 9-4N: The Way Back is Paved with Light IV",
    "Chapter 9N Nav Menu",
    "Christmas 2019 Event Guides Nav",
    "Christmas 2020 All-in-One Farming Guide",
    "Christmas 2020 Event Guides: A Snowy Night Capriccio Rerun",
    "Christmas 2022 E-1: A Person's Struggle",
    "Christmas 2022 E1-3: Buried Deception",
    "Christmas 2022 E1-4: Cherry Blossom Snowfall",
    "Christmas 2022 E-2: Heavy Metal and Tender Wood",
    "Christmas 2023 Event Guides: One Coin Short ReRun!",
    "Christmas E-1: Sangvis Orphan",
    "Christmas E-2: Mission: Dinergate",
    "Christmas E-3: X-Dinergates",
    "Christmas E-4: Ode to Gifts",
    "Christmas Event: A Snowy Night Capriccio Pre-Info",
    "Christmas ID Card Contest Voting (2019)",
    "Christmas2022Nav",
    "Clear guide template",
    "Clear guide template (New)",
    "Client Update v3.02, New Features",
    "Client Update v3.04 (and v3.03)",
    "Coalition Drill Weekly Teams",
    "Coalition Unit CSV Generator Test",
    "Combat and Logistics Guide: The Ultimate Logistics Frontlines",
    "Combat Bartender Action: Jill's Drink Mixing Guide",
    "Combat Missions List",
    "Continuum Turbulence All-in-One Farming Guide",
    "Continuum Turbulence Chapter 1 Clear Guides",
    "Continuum Turbulence Chapter 1 Nav Menu",
    "Continuum Turbulence Chapter 2 Clear Guides",
    "Continuum Turbulence Chapter 2 Nav Menu",
    "Continuum Turbulence Chapter 3 Clear Guides",
    "Continuum Turbulence Chapter 3 Nav Menu",
    "Continuum Turbulence Event Clear Guides",
    "Continuum Turbulence Preparation Guide",
    "Continuum Turbulence Ranking Rerun: Hurricane Rescue",
    "Continuum Turbulence Speed Run Event: Child of the Betrayer",
    "Corpse Dragging: How to Optimize Leveling",
    "Costume CSV Output Test",
    "Costume Shilling #1 clone: Why Does This Exist",
    "Costume Shilling #1: Why Does This Exist",
    "Costume Shilling #10.5: Medieval Throwback",
    "Costume Shilling #10: RACING HATH ARRIVED",
    "Costume Shilling #11: Tacticool at Last",
    "Costume Shilling #12.1: Guessing Game",
    "Costume Shilling #12.2: Rest of the Idiots",
    "Costume Shilling #13: error 404 AR team not found",
    "Costume Shilling #2: Chinese New Year",
    "Costume Shilling #3 Part 1: Zas is best girl",
    "Costume Shilling #3 Part 2: Wedding",
    "Costume Shilling #4 : Kimono",
    "Costume Shilling #5 Part 1: M4 Team",
    "Costume Shilling #5 Part 2: Groza Team",
    "Costume Shilling #5.5 Carnival Crinj",
    "Costume Shilling #6: LOLI GAMING",
    "Costume Shilling #7: Loli Gaming 2: Electric Boogaloo",
    "Costume Shilling #8: Cheek-y JS 9",
    "Costume Shilling #9: It's a Matter of Trust",
    "Costume Shilling #Bonus: Shilling Anniversary",
    "Costume Shilling #Error: A Summer with Ceia?",
    "Costume Shilling #Mars: SHARKIFUN",
    "Costume Shilling 14: Christmas MICA Style",
    "Costume Shilling Nav",
    "Costume Shilling: Anniversary Batch",
    "Countdown JS",
    "CT E1-1: Waste",
    "CT E1-10: Darkest Desire",
    "CT E1-2: Safe House",
    "CT E1-3:Auxiliary Power",
    "CT E1-4: Reserve Outpost",
    "CT E1-5:Last Day",
    "CT E1-6: Peace Negotiations",
    "CT E1-7: Fortunate?",
    "CT E1-8: Sangvis Elite Outpost",
    "CT E1-9: Neural Fragment",
    "CT E1-B1: Farewell Scarecrow",
    "CT E2-1: Unknown Enemy",
    "CT E2-2: Support",
    "CT E2-3: Griffin Expendables",
    "CT E2-4: Defense Outpost 2",
    "CT E2-5: Defense Outpost 3",
    "CT E2-6A: Just Kidding",
    "CT E2-6B: Defense Outpost 4",
    "CT E2-7A: General Offensive",
    "CT E2-7B: Exploratory Attack",
    "CT E2-8B: For the Future!",
    "CT E3-10: White Doll",
    "CT E3-2: Signal Flare",
    "CT E3-3A: Yellow Zone",
    "CT E3-3B: Red Zone",
    "CT E3-4A: Mark",
    "CT E3-4B: Vengeance",
    "CT E3-5: A New Hope",
    "CT E3-6: Vile Rats",
    "CT E3-7: Bad News",
    "CT E3-8: IED",
    "CT E3-9: Stumbling Block",
    "Deep Dive Guide",
    "Default De-ruins DJMax: A Farming Guide",
    "Destroyer (Protocol Assimilation)",
    "Dinergate (Protocol Assimilation)",
    "Division Collab E1-1 EX: Hudson Refugee Camp EX",
    "Division Collab E1-1: Hudson Refugee Camp",
    "Division Collab E1-2 EX: New York Library EX",
    "Division Collab E1-2: New York Library",
    "Division Collab E1-3 EX: Grand Central Terminal EX",
    "Division Collab E1-3: Grand Central Terminal",
    "Division Collab E1-4 EX: Dark Zone EX",
    "Division Collab E1-4: Dark Zone",
    "Division Collab E1-5 EX: Extraction Point EX",
    "Division Collab E1-5 EX: Extraction Point EX (old)",
    "Division Collab E1-5: Extraction Point",
    "Division Collab Farming 1: KSVK",
    "Division Collab Farming 2: UMP40",
    "Division Collab Farming 3: JS 9",
    "Division Collab Farming 4: DSR-50",
    "Division Collab Farming 5.2: OTs-14",
    "Division Collab Farming 5: OTs-14",
    "Division Collab: Grenade Farming!",
    "Division Collaboration Nav (EX Default)",
    "Division Collaboration Nav (NormalDefault)",
    "Division Minigame",
    "DJMax E1-1: Stalker",
    "DJMax E1-2: Heartbeat",
    "DJMax E1-3: Waiting for You",
    "DJMax E2-1: Sunset Rider",
    "DJMax E2-2: Fate",
    "DJMax E2-3: End of the Moonlight",
    "DJMax EX Stages",
    "DJMax EX1-1: Stalker EX",
    "DJMax EX1-2: Heartbeat EX",
    "DJMax EX1-3: Waiting for You EX",
    "DJMax EX2-1: Sunset Rider EX",
    "DJMax EX2-2: Fate EX",
    "DJMax EX2-3: End of the Moonlight EX",
    "DJMax Farming: Medals or Clears?",
    "DJMax Nav Menu",
    "DJMax Normal Stages",
    "DR Chapter 2 Nav",
    "DR Chapter 3 Nav",
    "Dragoon (Protocol Assimilation)",
    "Dreamer (Protocol Assimilation)",
    "Dual Randomness Chapter 1 Nav",
    "Dual Randomness Chapter 1: Departure Time 1",
    "Dual Randomness Chapter 1: Departure Time 1 EX",
    "Dual Randomness Chapter 1: Departure Time 2",
    "Dual Randomness Chapter 1: Departure Time 2 EX",
    "Dual Randomness Chapter 2: Pollinosis 1",
    "Dual Randomness Chapter 2: Pollinosis 10",
    "Dual Randomness Chapter 2: Pollinosis 2",
    "Dual Randomness Chapter 2: Pollinosis 3",
    "Dual Randomness Chapter 2: Pollinosis 4",
    "Dual Randomness Chapter 2: Pollinosis 5",
    "Dual Randomness Chapter 2: Pollinosis 6",
    "Dual Randomness Chapter 2: Pollinosis 7",
    "Dual Randomness Chapter 2: Pollinosis 8",
    "Dual Randomness Chapter 2: Pollinosis 9",
    "Dual Randomness Chapter 2: Pollinosis EX-1",
    "Dual Randomness Chapter 3: Ghost Sisters 1",
    "Dual Randomness Chapter 3: Ghost Sisters 10",
    "Dual Randomness Chapter 3: Ghost Sisters 2",
    "Dual Randomness Chapter 3: Ghost Sisters 3",
    "Dual Randomness Chapter 3: Ghost Sisters 4",
    "Dual Randomness Chapter 3: Ghost Sisters 5",
    "Dual Randomness Chapter 3: Ghost Sisters 6",
    "Dual Randomness Chapter 3: Ghost Sisters 7",
    "Dual Randomness Chapter 3: Ghost Sisters 8",
    "Dual Randomness Chapter 3: Ghost Sisters 9",
    "Dual Randomness Chapter 4 Nav",
    "Dual Randomness Chapter 4: Operation Snake Eater 1",
    "Dual Randomness Chapter 4: Operation Snake Eater 10",
    "Dual Randomness Chapter 4: Operation Snake Eater 2",
    "Dual Randomness Chapter 4: Operation Snake Eater 3",
    "Dual Randomness Chapter 4: Operation Snake Eater 4",
    "Dual Randomness Chapter 4: Operation Snake Eater 5",
    "Dual Randomness Chapter 4: Operation Snake Eater 6",
    "Dual Randomness Chapter 4: Operation Snake Eater 7",
    "Dual Randomness Chapter 4: Operation Snake Eater 8",
    "Dual Randomness Chapter 4: Operation Snake Eater 9",
    "Dual Randomness Chapter 5 Nav",
    "Dual Randomness Chapter 5: Infernal Enlightenment 1",
    "Dual Randomness Chapter 5: Infernal Enlightenment 2",
    "Dual Randomness Chapter 5: Infernal Enlightenment 3",
    "Dual Randomness Event Clear Guides",
    "Dual Randomness Farm Guide Nav",
    "Dual Randomness Interview",
    "Dual Randomness Master nav",
    "Dummy Page",
    "Dummy To Clone",
    "Duping Recommendations and Coalition Mooks",
    "E1-1 Departure Time Infinity Map Farming Guide",
    "E1-1: Seven-Step Puzzle",
    "E1-2: Corner Breaker",
    "E1-3: Layer Reversal",
    "E1-4: Side Collapse",
    "E1-9: Neural Fragment",
    "E2-1 Pollinosis Infinity Map Farming Guide",
    "E3-1 Ghost Sister Infinity Map Farming Guide",
    "E4-1 Operation Snake Eater Infinity Map Farming Guide",
    "E5-1 Infernal Enlightenment Infinity Map Farming Guide",
    "Eclipses and Saros :Thales Prediction(EX)",
    "Eclipses and Saros :Theia Impact (EX)",
    "Eclipses and Saros E1/E1-EX: First Contact",
    "Eclipses and Saros E2/E2-EX: Second Contact",
    "Eclipses and Saros E3/E3-EX: Totality",
    "Eclipses and Saros E4/E4-EX: Third Contact",
    "Eclipses and Saros Story Event Guides",
    "Empty Page, Placeholder, Null",
    "Enemy Introduction Index",
    "EoS Nav",
    "Equip Test",
    "Equipment Basics: How Equipment Work",
    "Equipment Generator Test",
    "Equipment List",
    "Executioner (Protocol Assimilation)",
    "Factory Basics: How to Build Your T-Doll Skynet Army",
    "Fairies",
    "Fairies: Where They Live and How to Craft Them",
    "Fairy Generator Test",
    "Fairy Index",
    "Fairy Rework Analysis (2022)",
    "Far Side of the Sea E-1: Island Getaway",
    "Far Side of the Sea E-2: Wheel of Fortune",
    "Far Side of the Sea E-3: Into the Dangerous Unknown",
    "Far Side of the Sea E-4: Last of the Summer Days",
    "Far Side of the Sea Rererun: Should you Farm?",
    "Featured Guides",
    "Featured Streams: Singularity",
    "featured test",
    "Fixed Point Against the Light II - E3-2",
    "Fixed Point Against the Light II UX - E3-2UX",
    "Fixed Point Blood Moon I - E3-4",
    "Fixed Point Blood Moon I UX - E3-4 UX",
    "Fixed Point Cangue-Breaking - E2-1",
    "Fixed Point Eclipse View - E3-5",
    "Fixed Point Eclipse View UX - E3-5 UX",
    "Fixed Point Event Clear Guides",
    "Fixed Point Farming Guide",
    "Fixed Point Intersection Point II - E3-3",
    "Fixed Point Intersection Point II UX - E3-3 UX",
    "Fixed Point Lonely Island I - E4-3",
    "Fixed Point Lonely Island I UX - E4-3 UX",
    "Fixed Point Lurking I - E2-2 (Hidden Achievement)",
    "Fixed Point Lurking III UX - E2-3 (Normal and UX)",
    "Fixed Point Master nav",
    "Fixed Point Nike II - E1-2",
    "Fixed Point Old Rain I - E4-2 (Hidden Achievement)",
    "Fixed Point Old Rain I UX - E4-2 UX (Hidden Achievement)",
    "Fixed Point Pursuit II - E1-1",
    "Fixed Point Rebirth I - E4-5",
    "Fixed Point Rebirth I UX - E4-5 UX",
    "Fixed Point Simulations (Minigames)",
    "Fixed Point Traitor I - E4-4",
    "Fixed Point Trample UX - E4-1 (Normal and UX) (Coallition Medals)",
    "Fixed Point Transverse Sectioning - E3-1",
    "Fixed Point Transverse Sectioning UX - E3-1UX",
    "Fixing GFL Client Lag (+ Possible Workarounds) (2021)",
    "Formation and Teambuilding Basics: How to Not Build a Pepega Echelon",
    "Formations Guide",
    "FP Chapter 1 Nav (Normal and UX Open)",
    "FP Chapter 2 Nav (Normal and UX Open)",
    "FP Chapter 3 Nav (Normal Open)",
    "FP Chapter 3 Nav (UX Open)",
    "FP Chapter 4 Nav (Normal Open)",
    "FP Chapter 4 Nav (UX Open)",
    "Freaky Pandemic Nav Menu",
    "Freedom from Core Hell: Corpse dragging on 10-4E with Carcano M91/38",
    "Future T-Dolls List",
    "Gager (Protocol Assimilation)",
    "Gamepress GFL Writer Applications Open!",
    "General Rate-Up Optimization: Polarized Light",
    "GFDB Introduction",
    "GFL Community Content Contest (2020)",
    "GFL Explained: Acquiring and Leveling HOC",
    "GFL Explained: AR/SMG Teambuilding",
    "GFL Explained: Basecamp and Exploration",
    "GFL Explained: Circuits and Tetris Minmax",
    "GFL Explained: Heavy Ordnance Corps",
    "GFL Explained: HOC Combat Basics",
    "GFL Explained: Neural Upgrade",
    "GFL Explained: Protocol Assimilation",
    "GFL Explained: Rate-Up",
    "GFL GamePress Bug Hunt and Giveaway Pilot Program and Twitter Launch",
    "GFL Newbie Help: by STEN and Skorpion",
    "GFL Stat Calc Test",
    "GFL Story Reader Test No Air",
    "GFL x DJMax Collab Glory Day Event Guides",
    "GFL x Gunslinger Girl Collab Dream Theatre Event Guides",
    "GFL x Jashin-Chan My Devil's Frontline Guides & Event Info",
    "Gingerbread Guard (Protocol Assimilation)",
    "Girls' Frontline 2: Exilium Closed Beta Signups Now Open!",
    "Girls' Frontline 2: Exilium Pre-Release Background Lore",
    "Girls' Frontline 6th Anniversary Livestream Recap",
    "Girls' Frontline AR Leveling Priority",
    "Girls' Frontline Beginner Support Guide #1 「Early Game Basics」",
    "Girls' Frontline Beginner Support Guide #2 「Types of T-Dolls & Unit Formations」",
    "Girls' Frontline Beginner Support Guide #3 「Resource and Item Acquisition」",
    "Girls' Frontline Beginner Support Guide #3.5 「Shop」",
    "Girls' Frontline Beginner Support Guide #4 「Raising T-Dolls」",
    "Girls' Frontline Beginner Support Guide #5 「Grinding and Core Acquisition」",
    "Girls' Frontline Beginner Support Guide #5.5 「Lore」",
    "Girls' Frontline Beginner Support Guide #6 「Night Battles」",
    "Girls' Frontline Beginner Support Guide #7 「Chapter 9, MGSG, and Kiting」",
    "Girls' Frontline Beginner Support Guide #7.5 「Fairies」",
    "Girls' Frontline Beginner Support Guide #8 「Neural Upgrade」",
    "Girls' Frontline Character Songs Collection ECHOES: English Translated Lyrics Included!",
    "Girls' Frontline eSports Season 2 Live Stream",
    "Girls' Frontline Events; Major, Minor Rate-ups and Others, Explained",
    "Girls Frontline Halloween Event Skins Announced",
    "Girls' Frontline II: Exilium - Everything we know in 2021",
    "Girls' Frontline Interview at Anime Expo 2018",
    "Girls' Frontline Lore:",
    "Girls' Frontline NPCs",
    "Girls' Frontline RF Leveling Priority",
    "Girls' Frontline Setting Exploration: Beilan Island Incident",
    "Girls' Frontline Setting Exploration: Collapse Technology",
    "Girls' Frontline Setting Exploration: ELID",
    "Girls' Frontline Setting Exploration: G&K Combat Forces",
    "Girls' Frontline Setting Exploration: Griffin & Kryuger VIPs",
    "Girls' Frontline Setting Exploration: Griffin and Kryuger PMC",
    "Girls' Frontline Setting Exploration: KCCO",
    "Girls' Frontline Setting Exploration: Lycoris & Persicaria",
    "Girls' Frontline Setting Exploration: Old Misha Mikhail Semenovich Tsvigun",
    "Girls' Frontline Setting Exploration: Paradeus",
    "Girls' Frontline Setting Exploration: Parapluie & OGAS",
    "Girls' Frontline Setting Exploration: Project Prometheus & Project Beacon",
    "Girls' Frontline Setting Exploration: Relic History",
    "Girls' Frontline Setting Exploration: Rossartrism",
    "Girls' Frontline Setting Exploration: Soviet VIPs",
    "Girls' Frontline Setting Exploration: State Security VIPs",
    "Girls' Frontline Setting Exploration: The Relic System, William, and OGAS",
    "Girls Frontline Staff and Community",
    "Girls' Frontline v2.0600 New Client FAQ (OUTDATED 2020)",
    "Girls' Frontline v2.0600 New Client Review (OUTDATED)",
    "Girls' Frontline v2.0700 New Client Review",
    "Girls' Frontline VA11 Hall-A Crossover Art Detailed",
    "Girls Frontline VA11 HALL-A Crossover Live in China, New Promo Video and Login Screen",
    "Girls Frontline Wiki - GamePress",
    "Girls' Frontline: Neural Cloud - Lore Overview",
    "Girls Frontline: Starting Out - Part 1",
    "Girls Frontline: Starting Out - Part 2",
    "Girls Frontline's Pre-Development History",
    "GitS SAC_2045 Collab: Through the Looking Glass",
    "GitS Through the Looking Glass NAV",
    "Glory Day Community Event: Pocket City Rumble (2020)",
    "Goliath Factory (Protocol Assimilation)",
    "GP Dialogue Name Hover JS/CSS",
    "Gray Zone Introduction",
    "Guard (Protocol Assimilation)",
    "Guide to GFChipCalc: HOC Calculator & Optimization Tool",
    "Guides",
    "Gunslinger Girl Collab E1-1: New Fork",
    "Gunslinger Girl Collab E1-2: Full Length Play II",
    "Gunslinger Girl Collab E1-3: Honest Pinocchio",
    "Gunslinger Girl Collab E1-5: That Which Must Be Protected",
    "Gunslinger Girl Collab EX1-1: New Fork EX",
    "Gunslinger Girl Collab EX1-2: Full-Length Play II EX",
    "Gunslinger Girl Collab EX1-3: Honest Pinocchio EX",
    "Gunslinger Girl Collab EX1-4: Garden of Old EX",
    "Gunslinger Girl Collab EX1-5 A: That Which Must Be Protected EX I",
    "Gunslinger Girl Collab EX1-5 B: That Which Must Be Protected EX II",
    "Gunslinger Girl Collab Nav EX",
    "Gunslinger Girl Collab Nav Normal",
    "Gunslinger Girl Collab: E1-4: Garden of Old",
    "Gunslinger Girl: Il Teatrino Collaboration Event Guides",
    "Halloween E-1 Clear Guide",
    "Halloween E-1 Farming Guide",
    "Halloween E-2 Clear Guide",
    "Halloween E-2 Farming Guide",
    "Halloween E-3 Clear Guide",
    "Halloween E-3 Farming Guide",
    "Halloween E-4 Clear Guide",
    "Halloween E-4 Farming Guide",
    "Halloween Event: Freaky Pandemic Guides",
    "Halloween Event: Freaky Pandemic Pre-Info",
    "Hanyang Christmas Shilling",
    "Heavy Production Guide",
    "HG Overviews",
    "HOC Circuit Board Scripts & Styles",
    "HOC CSV Generator Test",
    "HOC EXP Calculator",
    "HOC Guide Nav",
    "HOC Priority Guide",
    "HOC Rate-Up Analysis Priority: Who should I roll for?",
    "HOC Units",
    "HOC, Heavy Ordnance Corps Basics",
    "Hole 2 - Tide of Blood Madlad Farm",
    "How Frames & Rate of Fire Work",
    "How to Get Fwee Pawa (Free Parachute Fairy) Guide",
    "How to use: GF Battle Tester (Girls' Frontline Battle Tester)",
    "How to Use: GFAlarm (Girls' Frontline Alarm)",
    "How To Use: M4A1 Mod",
    "How To Use: Python",
    "How to: Quick Completion of Enemy Index",
    "Hunter (Protocol Assimilation)",
    "Icon Link CSS Mixin",
    "Inbox",
    "Intruder (Protocol Assimilation)",
    "Is 10-4E Right for You?",
    "Isomer 2020 Ranking Turn-by-Turn Walkthrough (ARCHIVE ONLY)",
    "Isomer Chapter 1 Clear Guides",
    "Isomer Chapter 1 EX",
    "Isomer Chapter 1 Nav - Default EX Tab",
    "Isomer Chapter 1 Nav - Default Normal Tab",
    "Isomer Chapter 1 Normal",
    "Isomer Chapter 2 Clear Guides",
    "Isomer Chapter 2 EX",
    "Isomer Chapter 2 Nav - Default EX Tab",
    "Isomer Chapter 2 Nav - Default Normal Tab",
    "Isomer Chapter 2 Normal",
    "Isomer Chapter 3 Clear Guides",
    "Isomer Chapter 3 EX",
    "Isomer Chapter 3 Nav - Default EX Tab",
    "Isomer Chapter 3 Nav - Default Normal Tab",
    "Isomer Chapter 3 Normal",
    "Isomer Chapter 4 Clear Guides",
    "Isomer Chapter 4 EX",
    "Isomer Chapter 4 Nav - Default EX Tab",
    "Isomer Chapter 4 Nav - Default Normal Tab",
    "Isomer Chapter 4 Normal",
    "Isomer Chapter Guides Nav",
    "Isomer E1-A1: Illusory Peace I",
    "Isomer E1-A1: Illusory Peace I EX",
    "Isomer E1-A3: Illusory Peace III/EX",
    "Isomer E1-B3: Cat And Mouse III",
    "Isomer E1-B3: Cat And Mouse III EX",
    "Isomer E1-B4: Cat And Mouse IV",
    "Isomer E1-B4: Cat And Mouse IV EX",
    "Isomer E1-C2: Beyond the Border II",
    "Isomer E1-C2: Beyond the Border II EX",
    "Isomer E1-C3: Beyond the Border III",
    "Isomer E1-C3: Beyond the Border III EX",
    "Isomer E1-Start: Souvenir",
    "Isomer E2-A1: Faith of Blood I",
    "Isomer E2-A1: Faith of Blood I EX",
    "Isomer E2-A2: Faith of Blood II",
    "Isomer E2-A2: Faith of Blood II EX",
    "Isomer E2-B1: Wolf and Owl I",
    "Isomer E2-B1: Wolf and Owl I EX",
    "Isomer E2-B2: Wolf and Owl II",
    "Isomer E2-B2: Wolf and Owl II EX",
    "Isomer E2-B3: Wolf and Owl Battle III EX",
    "Isomer E2-B3: Wolf and Owl III",
    "Isomer E2-C1: Under the Wall I",
    "Isomer E2-C1: Under the Wall I EX",
    "Isomer E3-A1: Lost Bargaining Chip I",
    "Isomer E3-A1: Lost Bargaining Chip I EX",
    "Isomer E3-A3: Lost Bargaining Chip III",
    "Isomer E3-A3: Lost Bargaining Chip III EX",
    "Isomer E3-B1: Shark and Sea Battle I EX",
    "Isomer E3-B1: Shark and the Sea I",
    "Isomer E3-B3: Shark and Sea Battle III EX",
    "Isomer E3-B3: Shark and the Sea III",
    "Isomer E3-B4: Shark and Sea Battle IV EX",
    "Isomer E3-B4: Shark and the Sea IV",
    "Isomer E4-2: Above the Hubbub II",
    "Isomer E4-2: Above the Hubbub II EX",
    "Isomer E4-3/4: Above the Hubbub III/IV Normal/EX [Bike Chase Minigame]",
    "Isomer E4-5: Above the Hubbub V",
    "Isomer E4-5: Above the Hubbub V EX",
    "Isomer Event Clear Guides",
    "Isomer Ranking - Combat Basics & Dealing With Enemies (OUTDATED 2020)",
    "Isomer Ranking Guide - Introduction (OUTDATED 2020)",
    "Isomer Ranking: Reducing RNG for Higher Scores (OUTDATED 2020)",
    "Isomer: A Farming Guide",
    "Isomer+ Ranking Rerun: Reign of Chaos+ (2023)",
    "Jaeger (Protocol Assimilation)",
    "Jaguar (Protocol Assimilation)",
    "Jashin Collab E1-1: Enter the Witch",
    "Jashin Collab E1-1EX: Enter the Witch",
    "Jashin Collab E1-2: Frozen",
    "Jashin Collab E1-2EX: Frozen",
    "Jashin Collab E1-3: Breakneck Pursuit",
    "Jashin Collab E1-3EX: Breakneck Pursuit",
    "Jashin Collab E1-4: Zombie Apocalypse Survival Guide",
    "Jashin Collab E1-4EX: Zombie Apocalypse Survival Guide",
    "Jashin Collab E1-5: Destruction Regeneration",
    "Jashin Collab E1-5EX: Destruction Regeneration",
    "Jashin EX Focus",
    "Jashin EX Nav",
    "Jashin Farming Guide: Normal and EX routes",
    "Jashin Normal Focus",
    "Jashin Normal Nav",
    "Judge (Protocol Assimilation)",
    "Kalina's Shop and Gems",
    "Key Card / Bingo Event: Dessert Vanguard (2019)",
    "List of Forced Manual Dolls",
    "Longitudinal Strain - 13 Goldberg Variations - EX (e2-4ex)",
    "Longitudinal Strain - 13 Goldberg Variations - UX (e2-4ux)",
    "Longitudinal Strain - 22 Night on Bald Mountain - Normal/EX (e2-5)",
    "Longitudinal Strain - 22 Night on Bald Mountain - UX (e2-5ux)",
    "Longitudinal Strain - 26 Thus Spoke Zarathustra - Normal/EX (e1-4)",
    "Longitudinal Strain - 26 Thus Spoke Zarathustra - UX (e1-4ux)",
    "Longitudinal Strain - 30 Symphony No. 6 - Normal/EX (e3-5)",
    "Longitudinal Strain - 30 Symphony No. 6 - UX (e3-5ux)",
    "Longitudinal Strain - 32 1812 Overture - Normal/EX (e3-6)",
    "Longitudinal Strain - 32 1812 Overture - UX (e3-6ux)",
    "Longitudinal Strain - 3-α2 Wind, Sand and Stars (e1-1)",
    "Longitudinal Strain - 3-β2 Symphony No.2 in C Major (e2-1)",
    "Longitudinal Strain - 3-γ2 Courante (e3-1)",
    "Longitudinal Strain - 5-α6 Chaconne - Normal/EX (e1-2)",
    "Longitudinal Strain - 5-α6 Chaconne - UX (e1-2ux)",
    "Longitudinal Strain - 5-α8 Stradivarius' Magic - UX (e1-3ux)",
    "Longitudinal Strain - 5-β6 Symphony No. 9 - Normal/EX (e2-2)",
    "Longitudinal Strain - 5-β6 Symphony No. 9 - UX (e2-2ux) | Hidden Achievement 1",
    "Longitudinal Strain - 5-β8 The Firebird - UX (e2-3ux)",
    "Longitudinal Strain - 5-γ6 Hour of Grief - EX (e3-2ex)",
    "Longitudinal Strain - 5-γ6 Hour of Grief - UX (e3-2ux)",
    "Longitudinal Strain - 5-γ8 Torna a Surriento - UX (e3-3ux)",
    "Longitudinal Strain - 9 Ghost - Normal/EX (e3-4)",
    "Longitudinal Strain - 9 Ghost - UX (e3-4ux)",
    "Longitudinal Strain Event Clear Guides",
    "Longitudinal Strain Master nav",
    "Lore Directory",
    "Love Bakery 1: Terrible Guest",
    "Love Bakery 2: Secret Worker",
    "Love Bakery 3: Chocolate Workshop",
    "Love Bakery 4: White Celebration",
    "Love Bakery 5: Sweet Funpark",
    "Love Bakery Nav",
    "LS Chapter 1 Nav (Normal and UX Open)",
    "LS Chapter 2 Nav (Normal and UX Open)",
    "LS Chapter 3 Nav (Normal and UX Open)",
    "LS Chapter 4 Nav (Normal and UX Open)",
    "LS Chapter 5 Nav (Normal and UX Open)",
    "LS2 Minigames NAV (Normal and EX)",
    "Lycan Sanctuary - Hunter's Patrol (e1)",
    "Lycan Sanctuary - Pond of Demons EX (e5ex)",
    "Lycan Sanctuary - Signal Fire (e6)",
    "Lycan Sanctuary - Signal Fire EX (e6ex)",
    "Lycan Sanctuary - Target or Trap (e3)",
    "Lycan Sanctuary - Target or Trap EX (e3ex)",
    "Lycan Sanctuary - Twilight Labyrinth I (e4-1)",
    "Lycan Sanctuary - Twilight Labyrinth II (e4-2)",
    "Lycan Sanctuary - Twilight Labyrinth III (e4-3)",
    "Lycan Sanctuary - Twilight Labyrinth IV (e4-4)",
    "Lycan Sanctuary - Twilight Labyrinth V (e4-5)",
    "Lycan Sanctuary - Witch's Tent EX (e2ex)",
    "M2",
    "M200 Sings Something Predictions Panel! (2020)",
    "Machine (PA)",
    "Making The Most Out Of EXP Boosts",
    "Making The Most Out Of Your EXP Boost",
    "Manticore (Protocol Assimilation)",
    "Melee (PA)",
    "MG Overviews",
    "MGs, SGs and Teambuilding",
    "MICA Broke the Fairy Tutotal",
    "Mirror STage Ch1 Nav (EX Open)",
    "Mirror STage Ch2 Nav (EX Open)",
    "Mirror STage Ch2 Nav (Normal Open)",
    "Mirror Stage ch3 Nav (EX Open)",
    "Mirror Stage ch3 Nav (Normal Open)",
    "Mirror Stage chapter 4 (EX Open)",
    "Mirror Stage chapter 4 (Normal Open)",
    "Mirror Stage Event Clear Guides",
    "Mirror Stage Interview with Yuzhong and the Writing Team (2021)",
    "Mirror Stage Master Nav",
    "Mirror Stage Ranking Points Farming Guide (2022)",
    "Mirror Stage: Achilles and the Tortoise II",
    "Mirror Stage: An Arrow in Flight II",
    "Mirror Stage: Ariadne's Clew II",
    "Mirror Stage: Ariadne's Clew II EX",
    "Mirror Stage: Atropos' Shears II",
    "Mirror Stage: Atropos' Shears II EX",
    "Mirror Stage: Birth of Apate II",
    "Mirror Stage: Birth of Apate II EX",
    "Mirror Stage: Brain in a Vat II",
    "Mirror Stage: Chaos' Abyss II",
    "Mirror Stage: Chaos' Abyss II EX",
    "Mirror Stage: Clotho's Thread II",
    "Mirror Stage: Clotho's Thread II EX",
    "Mirror Stage: Cratylus' River II",
    "Mirror Stage: Cretan Labyrinth II",
    "Mirror Stage: Cretan Labyrinth II EX",
    "Mirror Stage: Defying the Moerae II",
    "Mirror Stage: Defying the Moerae II EX",
    "Mirror Stage: Dreams on the Island of Dia II",
    "Mirror Stage: Dreams on the Island of Dia II EX",
    "Mirror Stage: Gaze",
    "Mirror Stage: Gaze EX",
    "Mirror Stage: Hemera Points III EX",
    "Mirror Stage: Hemera Points to the Light III",
    "Mirror Stage: Heraclitus' River II",
    "Mirror Stage: Hypnos' Eyes II",
    "Mirror Stage: Hypnos' Eyes II EX",
    "Mirror Stage: Lachesis' Measure II",
    "Mirror Stage: Lachesis' Measure II EX",
    "Mirror Stage: Nyx's Night III",
    "Mirror Stage: Nyx's Night III EX",
    "Mirror Stage: Pandora's Box II",
    "Mirror Stage: Ship of Theseus II",
    "Mirror Stage: Ship of Theseus II EX",
    "Mirror Stage: Shoulders of Griffin II",
    "Mirror Stage: Shoulders of Griffon II EX",
    "Mirror Stage: Thanatos Kiss II",
    "Mirror Stage: Thanatos Kiss II EX",
    "Mirror Stage: The Grain of Millet II",
    "Mirror Stage: The Imaginary",
    "Mirror Stage: The Imaginary EX",
    "Mirror Stage: The Prisioner's Dilemma II",
    "Mirror Stage: The Real",
    "Mirror Stage: The Real EX",
    "Mirror Stage: The Symbolic",
    "Mirror Stage: The Symbolic EX",
    "Mirror Stage: Torricelli's Trumpet II",
    "Mirror Stage: Wrestling Snakes I",
    "Mirror Stage: Wrestling Snakes I EX",
    "Mk 153 SMAW",
    "Mk 47",
    "Monthly Q&A: September 2019",
    "Monthly Roadmap: April 2020",
    "Monthly Roadmap: April 2021",
    "Monthly Roadmap: April 2022",
    "Monthly Roadmap: April 2023",
    "Monthly Roadmap: August 2020",
    "Monthly Roadmap: August 2021",
    "Monthly Roadmap: August 2022",
    "Monthly Roadmap: December 2019",
    "Monthly Roadmap: December 2020",
    "Monthly Roadmap: December 2021",
    "Monthly Roadmap: December 2023",
    "Monthly Roadmap: February 2020",
    "Monthly Roadmap: February 2021",
    "Monthly Roadmap: February 2022",
    "Monthly Roadmap: February 2023",
    "Monthly Roadmap: January 2020",
    "Monthly Roadmap: January 2021",
    "Monthly Roadmap: January 2022",
    "Monthly Roadmap: January 2023 (Fixed Point)",
    "Monthly Roadmap: July 2020",
    "Monthly Roadmap: July 2022",
    "Monthly Roadmap: June 2020",
    "Monthly Roadmap: June 2022",
    "Monthly Roadmap: June 2024",
    "Monthly Roadmap: March 2020",
    "Monthly Roadmap: March 2021",
    "Monthly Roadmap: March 2022",
    "Monthly Roadmap: March 2023",
    "Monthly Roadmap: May 2020",
    "Monthly Roadmap: May 2022",
    "Monthly Roadmap: November 2019",
    "Monthly Roadmap: November 2020",
    "Monthly Roadmap: November 2021",
    "Monthly Roadmap: November 2022",
    "Monthly Roadmap: November 2023 (v3.02)",
    "Monthly Roadmap: October 2019",
    "Monthly Roadmap: October 2020",
    "Monthly Roadmap: October 2021",
    "Monthly Roadmap: October 2022 (Poincare Recurrence Prep)",
    "Monthly Roadmap: September 2019",
    "Monthly Roadmap: September 2020",
    "Monthly Roadmap: September 2021",
    "Monthly Roadmap: September 2022 (Singularity+ Ranking)",
    "MS Ch1 Nav (Normal Open)",
    "Music of DJMax + GFL: Glory Day Stage BGM Compilation",
    "Nemeum (Protocol Assimilation)",
    "Neural Cloud: Exception Protocol Advanced Explained",
    "Neural Upgrade Priority Guide",
    "Neural Upgrade: How to Mod T-Dolls",
    "Neural Upgrade: Who do I vote for?",
    "New Career Quests and Progression",
    "New Career Quests and Progression: Building Your First Two Teams",
    "New Career Quests and Progression: Full List of Quest Rewards",
    "New Career Quests and Progression: Gem Shop and Spending Priorities",
    "New Career Quests and Progression: How to Start in Girls’ Frontline",
    "New Career Quests and Progression: Resource Allocation and Upgrades",
    "New Enemies AW",
    "New Enemies Ch10 and Singu",
    "New Enemies CT",
    "New Enemies DD",
    "New Enemies DR",
    "New Enemies FP",
    "New Enemies GFL",
    "New Enemies Iso",
    "New enemies LS",
    "New Enemies MS",
    "New Enemies PL",
    "New Enemies PR",
    "New Enemies SC",
    "New Enemies SS",
    "New GFL Anime, Jashin-chan collab, Welrod Mod III and More: GFL Jan 2021 Dev Stream Recap",
    "New GFL Client Update Fixes Lag Issues",
    "New Girls Frontline Figures Announced at Wonder Festival 2020!",
    "New Player Hub: How to Girls' Frontline",
    "New Player Priorities: Maximizing Resource Management, T-Doll Production, and Leveling",
    "News",
    "October Rescue Event Leak",
    "Official Girls' Frontline x Gunslinger Girl Collaboration Guide (2020)",
    "OLD DO NOT USE True Core Mask: Who to Get?",
    "One Coin Short Farming Guide",
    "Operation Burning Griffin - Girls' Frontline New Year Festival (2021)",
    "Operation Cube Guide",
    "Operation Cube+ Guide",
    "Operation Rabbit Hunt Guide",
    "Optimal SG Recipe: 6/2/6/4 vs. 8/1/8/4",
    "Optimizing Leveling: Introduction",
    "Optimizing Leveling: Lvl 1 ~ 70",
    "Optimizing Leveling: Lvl 70 ~ 90+",
    "Ouroboros (Protocol Assimilation)",
    "OUTDATED (Singularity 2019 Ranking on a Budget)",
    "Pity Embed",
    "PL Page Template",
    "Pocket City Rumble: Final Rankings & Showcase (2020)",
    "Poincaré Recurrence 1-Infi Farm",
    "Poincaré Recurrence 2-Infi Farm",
    "Poincaré Recurrence Chapter 1-1 (1-3 in-game)",
    "Poincaré Recurrence Chapter 1-2 (1-6 in-game)",
    "Poincaré Recurrence Chapter 1-2 EX (1-6 EX in-game)",
    "Poincaré Recurrence Chapter 1-3 (1-9 in-game)",
    "Poincaré Recurrence Chapter 1-4 (1-13 in-game)",
    "Poincaré Recurrence Chapter 1-4 EX (1-13 EX in-game)",
    "Poincaré Recurrence Chapter 2-1 (2-3 in-game)",
    "Poincaré Recurrence Chapter 2-1 EX (2-3 EX in-game)",
    "Poincaré Recurrence Chapter 2-2 (2-7 in-game)",
    "Poincaré Recurrence Chapter 2-2 EX (2-7 EX in-game)",
    "Poincaré Recurrence Chapter 2-3 (2-10 in-game)",
    "Poincaré Recurrence Chapter 2-4 (2-13 in-game)",
    "Poincaré Recurrence Chapter 2-4 EX (2-13 EX in-game)",
    "Poincaré Recurrence Chapter 3-1 (3-3 in-game)",
    "Poincaré Recurrence Chapter 3-1 EX (3-3 EX in-game)",
    "Poincaré Recurrence Chapter 3-2 (3-7 in-game)",
    "Poincaré Recurrence Chapter 3-3 (3-11 in-game)",
    "Poincaré Recurrence Chapter 3-3 EX (3-11 EX in-game)",
    "Poincaré Recurrence Chapter 3-4 (3-13 in-game)",
    "Poincaré Recurrence Chapter 3-4 EX (3-13 EX in-game)",
    "Poincaré Recurrence Chapter 4-1 (4-4 in-game)",
    "Poincaré Recurrence Chapter 4-1 EX (4-4 EX in-game)",
    "Poincaré Recurrence Chapter 4-2 (4-6 in-game)",
    "Poincaré Recurrence Chapter 4-3 (4-8 in-game)",
    "Poincaré Recurrence Chapter 4-3 EX (4-8 EX in-game)",
    "Poincaré Recurrence Chapter 4-4 (4-10 in-game)",
    "Poincaré Recurrence Chapter 4-4 EX (4-10 EX)",
    "Poincaré Recurrence Chapter 4-6 EX",
    "Poincaré Recurrence Chapter 5-1 (5-2 in-game)",
    "Poincaré Recurrence Chapter 5-1 EX (5-2 EX in-game)",
    "Poincaré Recurrence Chapter 5-2 (5-4 in-game)",
    "Poincaré Recurrence Chapter 5-2 EX (5-4 EX in-game)",
    "Poincaré Recurrence Chapter 5-3 (5-7 in-game)",
    "Poincaré Recurrence Chapter 5-3 EX (5-7 EX in-game)",
    "Poincaré Recurrence Chapter 5-4 (5-10 in-game)",
    "Poincaré Recurrence Chapter 5-4 EX (5-10 EX in-game)",
    "Poincaré Recurrence Chapter 6-1 (6-3 in-game)",
    "Poincaré Recurrence Chapter 6-1 EX (6-3 EX in-game)",
    "Poincaré Recurrence Chapter 6-2 (6-5 in-game)",
    "Poincaré Recurrence Chapter 6-3 (6-8 in-game)",
    "Poincaré Recurrence Chapter 6-3 EX (6-8 EX in-game)",
    "Poincaré Recurrence Chapter 6-4 (6-10 in-game)",
    "Poincaré Recurrence Chapter 6-4 EX (6-10 EX in-game)",
    "Poincaré Recurrence Event Clear Guides",
    "Poincaré Recurrence Interview with Yuzhong & Writers (2022)",
    "Poincaré Recurrence Master nav",
    "Point Event: Battlefield Lotus (2020)",
    "Point Event: Entrance Exam (2019)",
    "Point Event: Hit-Hop (2021)",
    "Point Event: Springtime Operation (2020)",
    "Point Event: Verdandi's Lucky Charm (2020)",
    "Polarized Light Chapter 1 Nav",
    "Polarized Light Chapter 2 Nav",
    "Polarized Light Chapter 3 Nav",
    "Polarized Light Chapter 4 Nav",
    "Polarized Light Chapter 5 Nav",
    "Polarized Light Chapter EX Nav",
    "Polarized Light E1-1: Propagation II",
    "Polarized Light E1-2: Critical Angle II",
    "Polarized Light E1-3: Reflector II",
    "Polarized Light E1-4: Reflector III",
    "Polarized Light E1-5: Total Internal Reflection II",
    "Polarized Light E1-6: Reversibility II",
    "Polarized Light E2-1: Polarizer II",
    "Polarized Light E2-2: Polarizer III",
    "Polarized Light E2-3: Waveguide II",
    "Polarized Light E2-4: Interferometer II",
    "Polarized Light E2-5: Spectrometer II",
    "Polarized Light E3-1: Enantiomer Overload III",
    "Polarized Light E3-2: Recrystallization Resolution III",
    "Polarized Light E3-3: Shattered Plane of Polarization III",
    "Polarized Light E3-4: Asymmetric Induction II",
    "Polarized Light E4-1: Milling II",
    "Polarized Light E4-2: Preheating II",
    "Polarized Light E4-3: Foam Stabilization II",
    "Polarized Light E4-4: Annealing I",
    "Polarized Light E4-5: Annealing III",
    "Polarized Light E4-6: Tempering II",
    "Polarized Light E4-7: Cutting II",
    "Polarized Light E4-8: Silvering II",
    "Polarized Light E4-9: Silvering III",
    "Polarized Light E5-1: Observable Limits III",
    "Polarized Light E5-2: Light Cone Frame of Reference II",
    "Polarized Light E5-3: Blackbody Radiation II",
    "Polarized Light E5-4: Escape Acceleration II",
    "Polarized Light Event Clear Guides",
    "Polarized Light EX 1: Critical Angle I + II",
    "Polarized Light EX 2: Vacuum Tube",
    "Polarized Light EX 3: Challenge III",
    "Polarized Light EX 4: Challenge IV",
    "Polarized Light EX 5: Annealing",
    "Polarized Light Lore FAQ",
    "Polarized Light Master Nav",
    "Polarized Light: Escape Acceleration EX-1 (Ranking Map 2 EX)",
    "PP-93",
    "PR Chapter 1 Nav (EX Open)",
    "PR Chapter 1 Nav (Normal Open)",
    "PR Chapter 2 Nav (Ex Open)",
    "PR Chapter 2 Nav (Normal Open)",
    "PR Chapter 3 Nav (EX Open)",
    "PR Chapter 3 Nav (Normal Open)",
    "PR Chapter 4 Nav (Normal Open)",
    "PR Chapter 5 Nav (EX Open)",
    "PR Chapter 5 Nav (Normal Open)",
    "PR Chapter 6 Nav (EX Open)",
    "PR Chapter 6 Nav (Normal Open)",
    "PR Infi Farm Nav",
    "Profile, Adjutants and Friendship Store",
    "Project Neural Cloud - Character Showcase",
    "Project Neural Cloud - Everything We Know Part 1: Livestream",
    "Project Neural Cloud - Everything We Know Part 2: Beta Test",
    "Project Neural Cloud - Function Cards",
    "Project Neural Cloud - Live2D Gallery",
    "Project Neural Cloud Article Navigation",
    "Project Neural Cloud Breaking News Nav",
    "Project Neural Cloud Character Teaser Profiles",
    "Project Neural Cloud Pre-Exploration",
    "Project Neural Cloud Pre-Release Background Lore",
    "Project Neural Cloud: CBT Afterthoughts",
    "Protocol Assimilation 1 Star Units",
    "Protocol Assimilation 2 Star Units",
    "Protocol Assimilation Ringleaders",
    "Protocol Assimilation Units",
    "Protocol Assimilation, Coalition Basics and Teambuilding",
    "Protocol Assimilation: Early FAQs",
    "Protocol Assimilation: First Impressions (Revamped)",
    "Prowler (Protocol Assimilation)",
    "Q&A",
    "QLZ-04",
    "Ranged (PA)",
    "Research Basics",
    "Resource Allocation, Combat Sims and Forward Basecamp",
    "RF Overviews",
    "RFHG teambuilding",
    "Ripper (Protocol Assimilation)",
    "S-ACR christmas shilling",
    "SC+ Ranking Rerun: Flowers of the End+ (2024)",
    "Scarecrow - Demonic Abyss (Protocol Assimilation)",
    "Scarecrow (Protocol Assimilation)",
    "Scout (Protocol Assimilation)",
    "scrapped pnc cbt 2 article",
    "Sei Farming Guide",
    "Setting Exploration: Gunslinger Girl",
    "Setting Exploration: The Division",
    "SG Overviews",
    "Sharkitect Architect - NVW Model (Protocol Assimilation)",
    "Shattered Connexion Ch1 Nav (EXDefault)",
    "Shattered Connexion Ch1 Nav (Normal Default)",
    "Shattered Connexion Ch2 Nav (EX Default)",
    "Shattered Connexion Ch2 Nav (Normal Default)",
    "Shattered Connexion Ch3 Nav (EX Default",
    "Shattered Connexion Ch3 Nav (Normal Default",
    "Shattered Connexion Ch5 Nav (EX Default)",
    "Shattered Connexion Ch5 Nav (Normal Default)",
    "Shattered Connexion Chapter 1 Clear Guides",
    "Shattered Connexion Chapter 4 Nav (EX Default",
    "Shattered Connexion Chapter 4 Nav (Normal Default",
    "Shattered Connexion E1-1 EX: Quiet Presence EX",
    "Shattered Connexion E1-1: Quiet Presence",
    "Shattered Connexion E1-2 EX: Reunions with Old Friends EX",
    "Shattered Connexion E1-2: Reunions with Old Friends",
    "Shattered Connexion E1-3: Bound Spirit I",
    "Shattered Connexion E1-3EX: Bound Spirit I EX",
    "Shattered Connexion E2-1 EX: Bound Spirit II EX",
    "Shattered Connexion E2-1: Bound Spirit II",
    "Shattered Connexion E2-2 EX: Intangible Sigh I EX",
    "Shattered Connexion E2-2: Intangible Sigh I",
    "Shattered Connexion E2-3 EX: Nameless Exiles EX",
    "Shattered Connexion E2-3: Nameless Exiles",
    "Shattered Connexion E2-4 EX: Nameless Exiles II EX",
    "Shattered Connexion E2-4: Nameless Exiles II",
    "Shattered Connexion E3-1 EX: Fractured Cognition I EX",
    "Shattered Connexion E3-1: Fractured Cognition I",
    "Shattered Connexion E3-2 EX: Fractured Cognition II EX",
    "Shattered Connexion E3-2: Fractured Cognition II",
    "Shattered Connexion E3-3 EX: Fractured Cognition III EX",
    "Shattered Connexion E3-3: Fractured Cognition III",
    "Shattered Connexion E4-1 EX: Subsurface Homecoming II EX",
    "Shattered Connexion E4-1: Subsurface Homecoming II",
    "Shattered Connexion E4-2 EX: Isomer I EX",
    "Shattered Connexion E4-2: Isomer I",
    "Shattered Connexion E4-3 EX: Subsurface Homecoming III EX",
    "Shattered Connexion E4-3: Subsurface Homecoming III",
    "Shattered Connexion E4-4 EX: Isomer II EX",
    "Shattered Connexion E4-4: Isomer II",
    "Shattered Connexion E5-1 EX: A Rock and A Hard Place EX",
    "Shattered Connexion E5-1: A Rock and A Hard Place",
    "Shattered Connexion E5-2 EX: Operation Defang I-1 EX",
    "Shattered Connexion E5-2: Operation Defang I-1",
    "Shattered Connexion E5-3 EX: Operation Defang I-2 EX",
    "Shattered Connexion E5-3: Operation Defang I-2",
    "Shattered Connexion E5-4 EX: Operation Defang II EX",
    "Shattered Connexion E5-4: Operation Defang II",
    "Shattered Connexion E5-6 EX: Farewell Tallinn I-1 EX",
    "Shattered Connexion E5-6: Farewell Tallinn I-1",
    "Shattered Connexion E5-7 EX: Farewell Tallinn I-2 EX",
    "Shattered Connexion E5-7: Farewell Tallinn I-2",
    "Shattered Connexion Event Clear Guides",
    "Shilling template",
    "Should I Use MGs?",
    "Should you Farm: Butterfly in a Cocoon",
    "Should You Farm: Butterfly In A Cocoon ReRun Limited Drops",
    "Should you Farm: Christmas Event Rerun!",
    "Should you Farm: Christmas ReRerun",
    "Should you Farm: Continuum Turbulence Limited Drops",
    "Should You Farm: Dual Randomness Limited Drops",
    "Should you Farm: Eclipses and Saros",
    "Should you Farm: Far Side of the Sea",
    "Should You Farm: Freaky Pandemic Rerun",
    "Should you Farm: GFL x DJMax Collab Glory Day",
    "Should You Farm: Gunslinger Girl Collaboration",
    "Should you Farm: Isomer Edition",
    "Should You Farm: Jashin Collab Edition",
    "Should You Farm: Mirror Stage Limited Drops",
    "Should You Farm: Poincaré Recurrence Limited Drops",
    "Should you Farm: Polarized Light Limited Drops",
    "Should You Farm: Shattered Connexion Limited Drops?",
    "Should you Farm: Singularity Limited Drops",
    "Should you Farm: The Division Collab Bounty Feast",
    "Should You Farm: VA-11 HALL-A Rerun Edition",
    "Should You Farm? January Rescue Event",
    "Should You Farm? October Rescue Event",
    "Should You Farm? Special Equipment",
    "Should You Roll: Sep. 2020 Batch [C-93, SIG-556, CR-21, K-PDW]",
    "Singularity All-in-One Farming Guide",
    "Singularity Ch 3-Hidden: Goodbye Dragon Palace",
    "Singularity Ch: 1-A3 Exhaust III",
    "Singularity Ch: 1-A4 Exhaust IV",
    "Singularity Ch: 1-B2 Compression II",
    "Singularity Ch: 1-B3: Compression III",
    "Singularity Ch: 1-B4: Compression IV",
    "Singularity Ch: 1-C1: Reignition I",
    "Singularity Ch: 1-C2 Reignition II",
    "Singularity Ch: 1-C3 Reignition III",
    "Singularity Ch: 1-C4 Reignition IV",
    "Singularity Ch: 1-Hidden: Messenger",
    "Singularity Ch: 2-1: Splinter Point",
    "Singularity Ch: 2-A1 Queen’s Gambit",
    "Singularity Ch: 2-A2 Queen’s Gambit II",
    "Singularity Ch: 2-A3 Queen’s Gambit III",
    "Singularity Ch: 2-A4: Queen’s Gambit IV",
    "Singularity Ch: 2-B1 Castling I",
    "Singularity Ch: 2-B2 Castling II",
    "Singularity Ch: 2-B3 Castling III",
    "Singularity Ch: 2-B4 Castling IV",
    "Singularity Ch: 2-C1 Promotion I",
    "Singularity Ch: 2-C2 Promotion II",
    "Singularity Ch: 2-C3 Promotion III",
    "Singularity Ch: 2-D1 No Mate I",
    "Singularity Ch: 2-D2 No Mate II",
    "Singularity Ch: 2-D3 No Mate III",
    "Singularity Ch: 2-D4 No Mate IV",
    "Singularity Ch: 2-Hidden: Survivor",
    "Singularity Ch: 3-1 Last Resort I",
    "Singularity Ch: 3-2 Last Resort II",
    "Singularity Ch: 3-3 Last Resort III",
    "Singularity Ch: 3-4 Last Resort IV",
    "Singularity Ch: 3-5 Last Resort V",
    "Singularity Ch: 3-6 Endgame",
    "Singularity Ch:2-C4 Promotion IV",
    "Singularity Chapter 1 Hub",
    "Singularity Chapter 1-1 Starting Point",
    "Singularity Chapter 1-2: Splinter Point",
    "Singularity Chapter 1-A1: Exhaust I",
    "Singularity Chapter 1-A2: Exhaust II",
    "Singularity Chapter 1-B1: Compression I",
    "Singularity Chapter 2 Chapters",
    "Singularity Chapter 2 Hub",
    "Singularity Chapter 3 Chapters",
    "Singularity Chapter 3 Hub",
    "Singularity Chapter One Chapters",
    "Singularity Event Clear Guides",
    "Singularity Preparation Guide",
    "Skill Generator Test",
    "Slow Shock - AUT Death and Life UX (e1-8ux)",
    "Slow Shock - AUT Isle of the Dead UX (e1-7ux)",
    "Slow Shock - F12 The Architectonic Angelus of Millet UX (e3-4ux)",
    "Slow Shock - F15 Guernica EX (e3-5ex)",
    "Slow Shock - F15 Guernica UX (e3-5ux)",
    "Slow Shock - F18 The Last Judgment UX (e3-6ux)",
    "Slow Shock - F3 The Black Square UX (e3-1ux)",
    "Slow Shock - F6 Dull Red EX (e3-2ex)",
    "Slow Shock - F6 Dull Red UX (e3-2ux)",
    "Slow Shock - F9 The Gun Salute UX (e3-3ux)",
    "Slow Shock - L4 Circles in a Circle UX (e2-1ux)",
    "Slow Shock - SPR Composition B with Red UX (e1-4ux)",
    "Slow Shock - SPR Composition VI UX (e1-3ux)",
    "Slow Shock - SUM Life is a Struggle UX (e1-6ux)",
    "Slow Shock - SUM Path in the Forest UX (e1-5ux)",
    "Slow Shock - WTR Composition II UX (e1-2ux)",
    "Slow Shock - WTR The Hunters in the Snow UX (e1-1ux)",
    "Slow Shock Chapter 1 Nav",
    "Slow Shock Chapter 2 Nav",
    "Slow Shock Chapter 3 Nav",
    "Slow Shock Event Clear Guides",
    "Slow Shock Master nav",
    "SMG Overviews",
    "Special Rescue Event October 2023",
    "Springfield's Cafe and Luffberry Chess",
    "Standard Multiplicative Buffs/Debuffs",
    "Stella Farming Guide",
    "Striker (Protocol Assimilation)",
    "Summer 2 Nav",
    "Summer 2020 All-in-One Farming Guide",
    "Summer 2020 Nav Menu",
    "Summer 3 Nav Menu",
    "SWAP Aegis (Protocol Assimilation)",
    "SWAP Dragoon (Protocol Assimilation)",
    "SWAP Guard (Protocol Assimilation)",
    "SWAP Jaeger (Protocol Assimilation)",
    "SWAP Prowler (Protocol Assimilation)",
    "SWAP Ripper (Protocol Assimilation)",
    "SWAP Striker (Protocol Assimilation)",
    "SWAP Vespid (Protocol Assimilation)",
    "t dolls list test",
    "Tarantula (Protocol Assimilation)",
    "Tareus (Protocol Assimilation)",
    "T-Doll & Costume List",
    "T-Doll (PA)",
    "T-Doll Basics",
    "T-Doll Costumes List",
    "T-Doll Duping Guide (OUTDATED)",
    "T-Doll Enhancement Guide",
    "T-Doll Generator Test",
    "T-Doll Icon CSS Mixin",
    "T-Doll Production Guide",
    "T-Dolls By Craft Time",
    "T-Dolls List",
    "T-Dolls Test",
    "test",
    "test colorbox",
    "test commento",
    "test costume embed",
    "test featured items",
    "test manga node",
    "test scrollto",
    "test t doll table",
    "test timer [noair]",
    "testing new ad",
    "The Division Collab Bounty Feast Event Guides",
    "The GFL GamePress Theatre V Ranking",
    "The GFL GamePress Theatre VI Ranking",
    "The History of Girls' Frontline Part 1 - 1905-Cold War's End",
    "The History of Girls' Frontline Part 2 - Late 1980s-2029",
    "The History of Girls' Frontline Part 3 - Post-Beilan Island-2044",
    "The History of Girls' Frontline Part 4 - The Situation in Germany",
    "The History of Girls' Frontline Part 8 - The Butterfly Incident",
    "The History of Girls' Frontline Part 9 - Dolls of Today & Tomorrow",
    "The History of Girls’ Frontline Part 5 - World War III 2045-2051",
    "The History of Girls’ Frontline Part 6 - Post-War Period (2051-2053)",
    "The History of Girls’ Frontline Part 7 - Lycoris, Persicaria & 90wish",
    "The Wave Wrangler: Should you Farm?",
    "Theater 11 Guide",
    "Theater Betting Episode 0: Prelude",
    "Theater Betting Episode 1: Daybreak",
    "Theater Betting Episode 10: Derangement",
    "Theater Betting Episode 11: Lelouceia of the Re;surrection",
    "Theater Betting Episode 12: Impiety",
    "Theater Betting Episode 13: Chicken",
    "Theater Betting Episode 14: Strife",
    "Theater Betting Episode 15: Folly",
    "Theater Betting Episode 16: Tumbling Down",
    "Theater Betting Episode 17: Order",
    "Theater Betting Episode 18: Chaos",
    "Theater Betting Episode 19: Calm before the Storm",
    "Theater Betting Episode 2: Ataxia",
    "Theater Betting Episode 20: Final Countdown",
    "Theater Betting Episode 21: Ride On",
    "Theater Betting Episode 22: Roundabout",
    "Theater Betting Episode 3: Hell Rising",
    "Theater Betting Episode 4: Apprehension",
    "Theater Betting Episode 5: Mathemagician",
    "Theater Betting Episode 6: Exile",
    "Theater Betting Episode 7: The Disappearance of Suomi KP31",
    "Theater Betting Episode 8: Quest Start",
    "Theater Betting Episode 9: Redemption",
    "Theater Betting Nav",
    "Theater Betting Nav Season 2",
    "Theater Betting Nav Season 3",
    "Theater Betting Nav Season 4",
    "Theater Combat Guide",
    "Theater II Betting Episode 0: Shipped to Brazil",
    "Theater II Betting Episode 1: Ghost of Vote C Past",
    "Theater II Betting Episode -1: YOOOOOOOOOOOOO",
    "Theater II Betting Episode 10: Catastrophe",
    "Theater II Betting Episode 11.5: Phishing",
    "Theater II Betting Episode 11: Cleista is Dead",
    "Theater II Betting Episode 12: Piety",
    "Theater II Betting Episode 12: Piety (Real)",
    "Theater II Betting Episode 13: Stickbug",
    "Theater II Betting Episode 14: Groundhog Day",
    "Theater II Betting Episode 15: Para-gone",
    "Theater II Betting Episode 16: Overtake",
    "Theater II Betting Episode 17: C-hair Force",
    "Theater II Betting Episode 18: Friday Night",
    "Theater II Betting Episode 19: Reckoning",
    "Theater II Betting Episode 2: C-AAAAAH",
    "Theater II Betting Episode 20: Ghost of Vote A Present",
    "Theater II Betting Episode 21: ReverEN-C-e",
    "Theater II Betting Episode 22.5: Trial by Fire",
    "Theater II Betting Episode 22: Dual Awkwardness",
    "Theater II Betting Episode 23: S09's Favorite Show",
    "Theater II Betting Episode 3: Newton's Third Law",
    "Theater II Betting Episode 4: Karmotrine Dream",
    "Theater II Betting Episode 5: EN's Box",
    "Theater II Betting Episode 6: ENhancement",
    "Theater II Betting Episode 7: ScrAAAAApped",
    "Theater II Betting Episode 8.5: From Brazil with Love",
    "Theater II Betting Episode 8: With the Fishes",
    "Theater II Betting Episode 9: Fringe Weaving",
    "Theater III Betting Episode 0: Emergency Meeting",
    "Theater III Betting Episode 1: Mitosis",
    "Theater III Betting Episode 10: Retribution",
    "Theater III Betting Episode 11: Denial",
    "Theater III Betting Episode 12: Just Desserts",
    "Theater III Betting Episode 13: The Second Coming",
    "Theater III Betting Episode 15: Filtration",
    "Theater III Betting Episode 2: 7 Squared",
    "Theater III Betting Episode 3: Arise",
    "Theater III Betting Episode 4: Brainwashing",
    "Theater III Betting Episode 5: Error Margin",
    "Theater III Betting Episode 6: Ceia voted A",
    "Theater III Betting Episode 7: Femme Furieuse",
    "Theater III Betting Episode 8: Consequences",
    "Theater III Betting Episode 9: Breaking Brekkie",
    "Theater III Betting Episodes 14+15: Apocalypse",
    "Theater III Betting Episodes 16+17: Decisive Victory",
    "Theater III Betting Template",
    "Theater IV Betting Episode 1: Baited",
    "Theater IV Betting Panel Episode -1: Collapse",
    "Theater Nav Season 5",
    "Theater System Full Guide (Outdated)",
    "Theater Teambuilding Guide (2021)",
    "Theater V Betting Afterparty: Karmotrine Dreams EX",
    "Theater V Betting: Episode I",
    "Theater V Betting: Episode II",
    "Theater V Betting: Episode III",
    "Theater V Betting: Episode IV + End",
    "Theater V Betting: Prologue Episode",
    "Through the Looking Glass - Breakthrough EX (e1ex)",
    "Through the Looking Glass - Ceaseless Mockery EX (e∞ex)",
    "Through the Looking Glass - Exception EX (e2ex)",
    "Through the Looking Glass - Judgement and Impediment EX (e4ex)",
    "Through the Looking Glass - Stolen Dreams (e5)",
    "Through the Looking Glass - Stolen Dreams EX (e5ex)",
    "Through the Looking Glass - Wish EX (e3ex)",
    "Tier List",
    "Tier List Copy",
    "Tier List Embeds",
    "Tier List Embeds Main",
    "Time to Mix Drinks and Change Lives: VA-11 Hall-A Collab Begins!",
    "TOOL: T-Doll Icon HTML Generator",
    "True Core Mask Revamped: Who to Get?",
    "Unarmored (PA)",
    "v3.01 Client Update: New Features (2022)",
    "VA Batch Preview (2019)",
    "VA-11 HALL-A Collab 1-1: Didgeridoo Tutorial Clear Guide",
    "VA-11 HALL-A Collab 1-1: Didgeridoo Tutorial Lite Clear Guide",
    "VA-11 HALL-A Collab 1-1EX: Didgeridoo Tutorial EX Clear Guide",
    "VA-11 HALL-A Collab 1-2: Adolescence Clear Guide",
    "VA-11 HALL-A Collab 1-2: Adolescence Clear Lite Guide",
    "VA-11 HALL-A Collab 1-2EX: Adolescence Clear EX Guide",
    "VA-11 HALL-A Collab 1-3: Pioneer Guide",
    "VA-11 HALL-A Collab 1-3: Pioneer Lite Guide",
    "VA-11 HALL-A Collab 1-3EX: Pioneer EX Guide",
    "VA-11 HALL-A Collab 1-4: Sonic Boom Guide",
    "VA-11 HALL-A Collab 1-4: Sonic Boom Lite Guide",
    "VA-11 HALL-A Collab 1-4EX: Sonic Boom EX Guide",
    "VA-11 HALL-A Collab 1-5: Chicken Breast Clear Guide",
    "VA-11 HALL-A Collab 1-5: Chicken Breast Lite Clear Guide",
    "VA-11 HALL-A Collab 1-5EX: Chicken Breast EX Clear Guide",
    "VA-11 HALL-A Collab 1-6: Fear of Public Speaking Guide",
    "VA-11 HALL-A Collab 1-6: Fear of Public Speaking Lite Guide",
    "VA-11 HALL-A Collab 1-6EX: Fear of Public Speaking EX Guide",
    "VA-11 HALL-A Collab 1-7: Truth or Dare Guide",
    "VA-11 HALL-A Collab 1-7: Truth or Dare Lite Guide",
    "VA-11 HALL-A Collab 1-7EX: Truth or Dare EX Guide",
    "VA-11 HALL-A Collab 1-8: The Last Rain in the World Guide",
    "VA-11 HALL-A Collab 1-8: The Last Rain in the World Lite Guide",
    "VA-11 HALL-A Collab 1-8EX: The Last Rain in the World EX",
    "VA-11 HALL-A Collab Guide",
    "VA-11 HALL-A Collab Hidden: Habanera Guide",
    "VA-11 HALL-A Stage Clear Guides",
    "VA-11 HALL-A x Girls' Frontline Collaboration Pre-Info",
    "valhalla drink and enemy image dump",
    "Vespid (Protocol Assimilation)",
    "VSK Christmas Shilling",
    "Waifu Wars #1 Part 1: We Fielding Waifus in Ranking?",
    "Waifu Wars #3: HGs and Leftovers",
    "Waifu Wars #4: Practical Applications",
    "Waifu Wars Polarized Light #2: Rifles",
    "Wave Wrangler 1: Tidal Bore",
    "Wave Wrangler 2: Rippling Dream",
    "Wave Wrangler 3: Pursuit",
    "Wave Wrangler 4: Zero Sum",
    "Weixin Interview with Yuzhong Translation (2021)",
    "What's New in GFL: Combat Sim Full Opening and EXP Boost Event",
    "What's New in GFL: Neural Upgrade & Rate-Up",
    "What's New in GFL: T-Doll Rescue & Halloween Events",
    "White Day 2020 Farming: A Companion Guide",
    "White Day All-in-One Farming Guide",
    "White Day Event Nav Menu",
    "White Day Stage 2: The Empty House",
    "White Day Stage 3: The Griffin Builder",
    "White Day Stage 4: The Missing MDR",
    "White Day Stage 5: The Crooked Man",
    "White Day Stage 6: The Seven Tangerine Pips",
    "White Day Stage 7: The Second Neural Cloud",
    "White Knight Fragment Farming Guide",
    "Worth Buying? GFL x Division Gem Shop Bundles",
    "Worth Playing? Girls' Frontline: Project Neural Cloud Review",
    "Zombie Bride (Corpse Bride) (Protocol Assimilation)",
    "Zombie Land Saga Collab Endings Guide:",
    "Zombie Land Saga Collab The Glistening Bloom"
];